### ISSUE TITLE
[turbopack] SVG via svgr support

### ISSUE THREAD

**Issue by pkolt** [vercel/turbo#4832]
### What version of Turborepo are you using?

next@13.4.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

In Next.js, I use the SVG image include using the svgr webpack plugin.

```typescript
// SiteLogo.svg
import LogoImage from 'public/images/logo.svg';
```

Next.js config:

```js
// next.config.js
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
  webpack(config) {
    // Support SVG (aviable )
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });
    return config;
  },
  output: 'export',
};

module.exports = nextConfig;
```

Unfortunately when using `next dev --turbo` I get errors:

```
- error Error: Cannot find module 'public/images/logo.svg'
```

### Expected Behavior

SVG pictures are loaded by picking up settings from `next.config.js` or by turbopack mechanisms.

### To Reproduce

Open repository

```
npm ci
npx next dev --turbo
```

### Reproduction Repo

https://github.com/pkolt/pkolt.ru

**Comment by cpotey** [comment]
To chime in, I'm getting similar issues with SVGR after upgrading to 13.4.1 too

I'm importing SVGs in from a `package/shared-ui/images` dir, and am getting 

```Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg xmlns="http://www.w3.org/2000/svg" ...></svg>``` 

Errors after importing/using in the Next 13.4 app router app (not in pages). Unsure whether this is a Next issue, or Turborepo one

**Comment by jridgewell** [comment]
We don't currently support SVGR loader natively, though it could probably be enabled using `experimental.turbo.loaders` config option in your `next.config.js`:

```js
module.exports = {
  experimental: {
    turbo: {
      loaders: {
        '.svg': ['@svgr/webpack'],
      },
    },
  },
};
```

- - -

Also @pkolt, the `'public/images/logo.svg'` specifier in your isn't support. To fix, you need to use `'../public/images/logo.svg'` (or whatever the appropriate number of `../`s) to import from your public directly. Alternatively, you could use `compilerOptions.paths` in `tsconfig.json` to remap importing from `public/*` to your public directory:

```json
{
  "compilerOptions": {
    "paths": {
      "public/*": ["./public/*"]
    }
  }
}
```

**Comment by pkolt** [comment]
Hi @jridgewell !

I tried to do what you described, but unfortunately it did not help me. I get an error:

<img width="971" alt="Снимок экрана 2023-05-10 в 19 24 09" src="https://github.com/vercel/turbo/assets/478905/172eee2a-0b42-4454-be6e-db48260bccef">

There is a`<svg>` root element in my picture, you can see for yourself:

https://github.com/pkolt/pkolt.ru/blob/master/public/images/calendar.svg?short_path=e465239#L0-L1

Thanks!

**Comment by iipanda** [comment]
> Hi @jridgewell !
> 
> I tried to do what you described, but unfortunately it did not help me. I get an error:
> <img alt="Снимок экрана 2023-05-10 в 19 24 09" width="971" src="https://user-images.githubusercontent.com/478905/237439710-172eee2a-0b42-4454-be6e-db48260bccef.png">
> 
> There is a`<svg>` root element in my picture, you can see for yourself:
> 
> https://github.com/pkolt/pkolt.ru/blob/master/public/images/calendar.svg?short_path=e465239#L0-L1
> 
> Thanks!

I have the same issue, is there any fix available for this?

**Comment by tntchn** [comment]
Found a related issue here [vercel:next.js#48140](https://github.com/vercel/next.js/issues/48140)

It was caused by turbopack trying to get the dimension of svg but webpack already turn the import into a function

**Comment by stevenmunro** [comment]
> Found a related issue here [vercel/next.js#48140](https://github.com/vercel/next.js/issues/48140)
> 
> It was caused by turbopack trying to get the dimension of svg but webpack already turn the import into a function

The whole world needs to know about this. I just fixed hours and hours of frustration by adopting this simple little change.

**Comment by osdiab** [comment]
Idk anything about how Turbopack nor Rust works but it seems

- [there is an import test for SVGs from a while ago](https://github.com/vercel/turbo/blob/f448cb5608884d76bae31c9e90635c1f0a231fe1/crates/turbopack-tests/tests/snapshot/imports/static/input/index.js), not sure what the significance of that is
- [Turbopack seems to have a part that treats SVGs as a static asset like other image formats](https://github.com/vercel/turbo/blob/f448cb5608884d76bae31c9e90635c1f0a231fe1/crates/turbopack/src/module_options/mod.rs#L377), though again not sure what that means in practice.

Hoping that SVG support becomes built in or more formally supported without hacks like the above!

**Comment by tntchn** [comment]
This issue seemed to be resolved in the latest with-turbopack-loaders example with `rules` option in next.config.js

https://github.com/vercel/next.js/blob/17ba84b7a7774ca09917ec3fbf44074d534b5c12/examples/with-turbopack-loaders/next.config.js#L1-L16

Works for me in my project, however with this config, the usage of <Image src={SvgFile} alt='' /> is not possible as turbopack takes svg files as js files

**Comment by karldivad** [comment]
Thanks @tntchn. It worked for me on both configs, just for changing a fill color 🥳 
```
const nextConfig = {
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/i,
      use: ['@svgr/webpack'],
    })

    return config
  },
  experimental: {
    turbo: {
      rules: {
        '*.svg': {
          loaders: ['@svgr/webpack'],
          as: '*.js',
        },
      },
    },
  },
}
```

**Comment by dmythro** [comment]
Thanks, it works with Next.js v14 as well. Wondering when it finally transitions from experimental to stable :)

**Comment by michaelhays** [comment]
This is working as expected with `@svgr/webpack`, should this issue be closed?

**Comment by dmythro** [comment]
Using it like that for the last few days, didn't see issues so far.

But it was not so easy to find, so I'd close it after documenting properly.

Wondering when can it go out of "experimental" though.

**Comment by bettiolo** [comment]
Worked for me too, can be closed.

**Comment by Yihao-G** [comment]
How can I configure it if I want to keep the original `.svg` loader rule? Like the one documented on the [SVGR website](https://react-svgr.com/docs/next/#usage):

```javascript
module.exports = {
  webpack(config) {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module.rules.find((rule) =>
      rule.test?.test?.('.svg'),
    )

    config.module.rules.push(
      // Reapply the existing rule, but only for svg imports ending in ?url
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /url/, // *.svg?url
      },
      // Convert all other *.svg imports to React components
      {
        test: /\.svg$/i,
        issuer: fileLoaderRule.issuer,
        resourceQuery: { not: [...fileLoaderRule.resourceQuery.not, /url/] }, // exclude if *.svg?url
        use: ['@svgr/webpack'],
      },
    )

    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i

    return config
  },

  // ...other config
}
```

**Comment by Yihao-G** [comment]
> Which version of framework you are using ?

I'm using Nextjs 14.2.3

**Comment by daaain** [comment]
If I understood right from the [turbo docs page](https://nextjs.org/docs/architecture/turbopack#unsupported-features), the `webpack()` bit is pointless, it won't be used. Putting a `console.log()` in there I didn't get any output, so by all means seems to be true.

There's the [with-turbopack-loaders](https://github.com/vercel/next.js/tree/17ba84b7a7774ca09917ec3fbf44074d534b5c12/examples/with-turbopack-loaders) example in the repo that covers this usecase and currently works with latest Next.js.

This all being said, I've wasted a few hours on this and just can't get it working with Typescript, always getting back `{"src":"/_next/static/media/data-sources.b4ce7cbe.svg","width":24,"height":24,"blurDataURL":null,"blurWidth":0,"blurHeight":0}` instead of a component, no matter what I try...

**Comment by mirismaili** [comment]
Like @Yihao-G I still have problem with loading `.svg`s using TurboPack. I want to configure the boundler to load `.svg`s in two ways (as a the default way in Next.js or using SVGR) and this is my webpack configuration:
```js
webpack(config) {
  const defaultSvgLoader = config.module.rules.find((rule) => rule.test?.test?.('.svg'))
  config.module.rules.push(
    {
      ...defaultSvgLoader,
      test: /\.svg$/i,
      resourceQuery: {not: [...defaultSvgLoader.resourceQuery.not, /react/]}, // exclude if *.svg?react
    },
    {
      test: /\.svg$/i,
      issuer: defaultSvgLoader.issuer, // issuer: /\.[jt]sx?$/ doesn't work:
      // https://github.com/vercel/next.js/issues/48177#issuecomment-1506251112
      resourceQuery: /react/, // *.svg?react
      use: '@svgr/webpack',
    },
  )
  // config.optimization = {minimize: false}
  return config
}
```
As you can see, I can use `?react` query to tell the boundler that I want a React component. But w/o it, it works regularly.

How can I configure the similar behaviour for TurboPack?

**Comment by judewang** [comment]
@mirismaili Turbopack doesn't support resourceQuery. We can import SVG as React component without passing "?react". If we want to use SVG image as `src` of an Image component, we don't have to statically import the SVG image, we can just pass the public path like `/logo.svg` as the `src` property. The downside is that we need to add `width`, `height` props, but it's ok for me as a workaround.

**Comment by stevenmunro** [comment]
> Like @Yihao-G I still have problem with loading `.svg`s using TurboPack. I want to configure the boundler to load `.svg`s in two ways according to my `import` method. If I just `import` it, it should be imported regularly (the default way in Next.js). And if I `import` it using `?react` resource-query, it should be imported using SVGR.
> 
> And this is my webpack configuration:
> 
> ```js
> webpack(config) {
>   const defaultSvgLoader = config.module.rules.find((rule) => rule.test?.test?.('.svg'))
>   config.module.rules.push(
>     {
>       ...defaultSvgLoader,
>       test: /\.svg$/i,
>       resourceQuery: {not: [...defaultSvgLoader.resourceQuery.not, /react/]}, // exclude if *.svg?react
>     },
>     {
>       test: /\.svg$/i,
>       issuer: defaultSvgLoader.issuer, // issuer: /\.[jt]sx?$/ doesn't work:
>       // https://github.com/vercel/next.js/issues/48177#issuecomment-1506251112
>       resourceQuery: /react/, // *.svg?react
>       use: '@svgr/webpack',
>     },
>   )
>   // config.optimization = {minimize: false}
>   return config
> }
> ```
> 
> As you can see, I can use `?react` query to tell the boundler that I want a React component. But w/o it, it should be imported regularly (as `StaticImageData` (`from 'next/image'`)).
> 
> How can I configure the similar behaviour for TurboPack?

I use this method to allow me to use `.svg` with the `next/image` component, and embed certain svgs as required.

Rename the svgs to be embedded from `.svg` to `.svgr`

Pop this into your `next.config.js` file.

```js
  experimental: {
    turbo: {
      rules: {
        "*.svgr": {
          loaders: ["@svgr/webpack"],
          as: "*.js"
        }
      }
    }
  }
```

If you're using TypeScript..

Create or update your `types.d.ts` or `global.d.ts` file in your project (usually in the src or root folder).

Add the following declaration for *.svgr files

```ts
declare module "*.svgr" {
  const content: React.FunctionComponent<React.SVGProps<SVGSVGElement>>;
  export default content;
}
```

In your document..

```js
import EmbeddedSVG from "@/public/images/steven.svgr";
```

```jsx
<EmbeddedSVG className="flex-shrink-0 w-16 h-auto text-[#BADA55] fill-current" />
```

**Comment by TryV** [comment]
> How can I configure the similar behaviour for Turbopack?

I did it by adding another suffix to my images. There was no other way (yet).

```json
{
	experimental: {
		turbo: {
			rules: {
				'*.inline.svg': {
					loaders: ['@svgr/webpack'],
					as: '*.js',
				}
			}
		}
	}
}
```

**Comment by Connoropolous** [comment]
> If I understood right from the [turbo docs page](https://nextjs.org/docs/architecture/turbopack#unsupported-features), the `webpack()` bit is pointless, it won't be used.

Oddly enough, I'm on nextjs 15, and I was experiencing like @Anishali2 that it worked if I used both the webpack config and the turbo config in my next.config.js file.

**Comment by apetta** [comment]
> > If I understood right from the [turbo docs page](https://nextjs.org/docs/architecture/turbopack#unsupported-features), the `webpack()` bit is pointless, it won't be used.
> 
> Oddly enough, I'm on nextjs 15, and I was experiencing like @Anishali2 that it worked if I used both the webpack config and the turbo config in my next.config.js file.

Yeah same for me. It looks like turbopack is only available/used for the `dev` and not for the `build` command...

**Comment by creators-studio** [comment]
> > > If I understood right from the [turbo docs page](https://nextjs.org/docs/architecture/turbopack#unsupported-features), the `webpack()` bit is pointless, it won't be used.
> > 
> > 
> > Oddly enough, I'm on nextjs 15, and I was experiencing like [@Anishali2](https://github.com/Anishali2) that it worked if I used both the webpack config and the turbo config in my next.config.js file.
> 
> Yeah same for me. It looks like turbopack is only available/used for the `dev` and not for the `build` command...

My current approach is the following:
```typescript
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/i,
      include: /src\/assets\/.*\.svg$/, // this allows icon.svg in app dir to work. All SVGs to be handled by SVGR are in src/assets
      use: ["@svgr/webpack"],
    });

    return config;
  },
  experimental: {
    turbo: {
      rules: {
        "*.svg": {
          loaders: ["@svgr/webpack"],
          as: "*.js",
        },
      },
    },
  },
};

export default nextConfig;
```

All SVGs that need to be processed by SVGR are placed in `src/assets`. This helps me avoid the `...app/icon.svg?__next_metadata__" is not a valid image file` error when building.

**Comment by albert-sway** [comment]
For anyone who comes across this now that `turbopack` is stable (`next@^15.3`), the below config is what you'll want (no longer in the `experimental.turbo` object).

```typescript
import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  turbopack: {
    rules: {
      '*.svg': {
        loaders: ['@svgr/webpack'],
        as: '*.js',
      },
    },
  },
};

export default nextConfig;
```

**Comment by rinaldycodes** [comment]
> turbopack: {
>     rules: {
>       '*.svg': {
>         loaders: ['@svgr/webpack'],
>         as: '*.js',
>       },
>     },
>   },

 Unrecognized key(s) in object: 'turbopack' i got error in commandline

**Comment by rinaldycodes** [comment]
> > turbopack: {
> > rules: {
> > '_.svg': {
> > loaders: ['@svgr/webpack'],
> > as: '_.js',
> > },
> > },
> > },
> 
> Unrecognized key(s) in object: 'turbopack' i got error in commandline

i fixed update next js 15.2 into 15.3

**Comment by oh3vci** [comment]
This works in version 15.3 and above.

```ts
import { type NextConfig } from 'next';

const nextConfig: NextConfig = {
  turbopack: {
    rules: {
      '*.svg': {
        as: '*.js',
        loaders: ['@svgr/webpack'],
      },
    },
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/i,
      use: ['@svgr/webpack'],
    });
    return config;
  },
};

export default nextConfig;
```

**Comment by abhi-abhiram** [comment]
Don't forgot to add `--turbo` flag, if you are using only turbo.

**Comment by alarm109** [comment]
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
This fixed the error above:


> This works in version 15.3 and above.
> 
> import { type NextConfig } from 'next';
> ```ts
> const nextConfig: NextConfig = {
>   turbopack: {
>     rules: {
>       '*.svg': {
>         as: '*.js',
>         loaders: ['@svgr/webpack'],
>       },
>     },
>   },
>   webpack(config) {
>     config.module.rules.push({
>       test: /\.svg$/i,
>       use: ['@svgr/webpack'],
>     });
>     return config;
>   },
> };
> ```
> export default nextConfig;

**Comment by brunobely** [comment]
Even after adding the next config, I get this import error in my @repo/ui package - tried adding `"**/*.svg"` to the `tsconfig.json` but that didn't help. Anybody solve that?

```Cannot find module './xyz.svg' or its corresponding type declarations.ts(2307)```

**Comment by YarikDrago** [comment]
> For anyone who comes across this now that `turbopack` is stable (`next@^15.3`), the below config is what you'll want (no longer in the `experimental.turbo` object).
> 
> import type { NextConfig } from 'next';
> 
> const nextConfig: NextConfig = {
>   turbopack: {
>     rules: {
>       '*.svg': {
>         loaders: ['@svgr/webpack'],
>         as: '*.js',
>       },
>     },
>   },
> };
> 
> export default nextConfig;

I tested this solution in Next.js v16^ and it works!

**Comment by vitalets** [comment]
Since Next.js 16, you can also conditionally apply the SVGR loader to a particular directory (in turbopack):
```js
turbopack: {
  rules: {
    "*.svg": {
      loaders: ["@svgr/webpack"],
      condition: {
        path: "icons/**" // <-- apply only to 'icons' dir
      },
      as: "*.js",
    },
  },
},
```

But in my projects, I replaced `@svgr/webpack` with a custom loader, here's a detailed [write-up](https://dev.to/vitalets/turbopack-a-better-way-to-inline-svg-in-nextjs-16-36em).
