### ISSUE TITLE
[turborepo] Cannot find module 'turbo' when using docker to build

### ISSUE THREAD

**Issue by aindong** [vercel/turbo#3257]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I have been using turbo repo and building my apps using docker and was working perfectly with v1.6.3 until 1.7.0 released, the `turbo` cli can't be found after doing `yarn global add turbo` on docker. 

```
 => [installer 1/8] WORKDIR /app                                                                                                                0.2s
 => [runner 2/4] RUN addgroup --system --gid 1001 nodejs                                                                                        3.1s
 => [builder 2/4] RUN yarn global add turbo                                                                                                    30.7s
 => [runner 3/4] RUN adduser --system --uid 1001 ***                                                                                        2.0s
 => [installer 2/8] COPY .gitignore .gitignore                                                                                                  0.5s
 => [builder 3/4] COPY . .                                                                                                                      7.3s
 => ERROR [builder 4/4] RUN turbo prune --scope=*** --docker                                                                     1.6s
------
 > [builder 4/4] RUN turbo prune --scope=*** --docker:
#17 1.472 /app/node_modules/turbo/bin/turbo:13
#17 1.472     throw e;
#17 1.472     ^
#17 1.472
#17 1.472 Error: Cannot find module 'turbo'
#17 1.472 Require stack:
#17 1.472 - /app/node_modules/turbo/node-platform.js
#17 1.472 - /app/node_modules/turbo/bin/turbo
#17 1.472     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
#17 1.472     at Function.resolve (node:internal/modules/cjs/helpers:109:19)
#17 1.472     at downloadedBinPath (/app/node_modules/turbo/node-platform.js:44:44)
#17 1.472     at generateBinPath (/app/node_modules/turbo/node-platform.js:67:15)
#17 1.472     at Object.<anonymous> (/app/node_modules/turbo/bin/turbo:7:5)
#17 1.472     at Module._compile (node:internal/modules/cjs/loader:1155:14)
#17 1.472     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
#17 1.472     at Module.load (node:internal/modules/cjs/loader:1033:32)
#17 1.472     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
#17 1.472     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
#17 1.472   code: 'MODULE_NOT_FOUND',
#17 1.472   requireStack: [
#17 1.472     '/app/node_modules/turbo/node-platform.js',
#17 1.472     '/app/node_modules/turbo/bin/turbo'
#17 1.472   ]
#17 1.472 }
------
```

### Expected Behavior

Should be able to run turbo command `RUN turbo .....` on docker after installing turbo

### To Reproduce

Use this sample Dockerfile and build it
```
FROM --platform=linux/amd64 node:16.18-alpine AS base

RUN apk add --no-cache libc6-compat
RUN apk add --update --no-cache openssl1.1-compat
RUN apk update

WORKDIR /app
ARG SCOPE
ENV SCOPE=${SCOPE}

FROM base AS builder
# Set working directory
WORKDIR /app
RUN yarn global add turbo@${TURBO_VERSION}
COPY . .
RUN turbo prune --scope=${SCOPE} --docker
```

SCOPE is the `app` or `package` you want to build with docker

**Comment by aindong** [comment]
going backward with turbo@1.6.3 will solve the issue for now

**Comment by gsoltis** [comment]
Thanks for the report and repro! We'll take a look at this, it does appear to be a bug

**Comment by bibblebabl** [comment]
> Thanks for the report and repro! We'll take a look at this, it does appear to be a bug

Same thing with `with-docker` example

**Comment by tknickman** [comment]
Hey, here's what appears to be going on. 

You're copying your entire directory here: `COPY . .` which is going to include your `node_modules/`. Now, when you run `turbo prune ...`, it's going to (correctly) defer to your local `turbo` here because it _does_ exist. However, because you copied from your local machine (mac), turbo will only have the `turbo-darwin-64` package installed instead of the `turbo-linux-64` package which it needs for alpine. 

I'm going to take a look at a fix for this on our end. In the meantime you can unblock by either:
1. Removing your local turbo `yarn remove turbo -W` and letting the global turbo that you're installing in the container handle everything
2. Run a `yarn install` after the `COPY . .` so turbo can install the correct version for your new environment (not ideal as this will be slower)

**Comment by bibblebabl** [comment]
@tknickman I'm having the same issue with [with-docker](https://github.com/vercel/turbo/tree/main/examples/with-docker) example. Here is a log:

```

➜  code npx degit vercel/turbo/examples/with-docker with-docker 
> cloned vercel/turbo#HEAD to with-docker 
➜  code cd with-docker 
➜  with-docker git init . && git add . && git commit -m "Init" 
Initialized empty Git repository in /Users/igorbelogurov/code/with-docker/.git/ 
➜  with-docker git:(main) docker network create app_network  
➜  with-docker git:(main) yarn install
➜  with-docker git:(main) COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml build 
[+] Building 27.1s (19/41)                                                                                                                                                                 
 => [with-docker-web internal] load build definition from Dockerfile                                                                                                                  0.0s 
 => => transferring dockerfile: 32B                                                                                                                                                   0.0s 
 => [with-docker-api internal] load build definition from Dockerfile                                                                                                                  0.0s 
 => => transferring dockerfile: 32B                                                                                                                                                   0.0s 
 => [with-docker-web internal] load .dockerignore                                                                                                                                     0.0s 
 => => transferring context: 32B                                                                                                                                                      0.0s 
 => [with-docker-api internal] load .dockerignore                                                                                                                                     0.0s 
 => => transferring context: 32B                                                                                                                                                      0.0s 
 => [with-docker-api internal] load metadata for docker.io/library/node:alpine                                                                                                       26.9s 
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                           0.0s 
 => [with-docker-web installer  1/11] FROM docker.io/library/node:alpine@sha256:ab3603cb7934b21f1ffb522b1a1d538809516c6e4cd73b144716bc1830aad1a6                                      0.0s 
 => [with-docker-api internal] load build context                                                                                                                                    23.4s 
 => => transferring context: 300.52MB                                                                                                                                                23.3s 
 => CACHED [with-docker-web runner 2/8] WORKDIR /app                                                                                                                                  0.0s 
 => CACHED [with-docker-web runner 3/8] RUN addgroup --system --gid 1001 nodejs                                                                                                       0.0s 
 => CACHED [with-docker-web runner 4/8] RUN adduser --system --uid 1001 nextjs                                                                                                        0.0s 
 => [with-docker-web internal] load build context                                                                                                                                    23.7s 
 => => transferring context: 300.52MB                                                                                                                                                23.6s 
 => CACHED [with-docker-web installer  2/11] RUN apk add --no-cache libc6-compat                                                                                                      0.0s 
 => CACHED [with-docker-web installer  3/11] RUN apk update                                                                                                                           0.0s 
 => CACHED [with-docker-web installer  4/11] WORKDIR /app                                                                                                                             0.0s 
 => CACHED [with-docker-web builder 5/7] RUN yarn global add turbo                                                                                                                    0.0s 
 => [with-docker-api builder 6/7] COPY . .                                                                                                                                            2.1s 
 => ERROR [with-docker-api builder 7/7] RUN turbo prune --scope=api --docker                                                                                                          0.4s 
 => CACHED [with-docker-web builder 6/7] COPY . .                                                                                                                                     0.0s 
 => ERROR [with-docker-web builder 7/7] RUN turbo prune --scope=web --docker                                                                                                          0.3s 
------ 
 > [with-docker-api builder 7/7] RUN turbo prune --scope=api --docker: 
#0 0.310 /app/node_modules/turbo/bin/turbo:13 
#0 0.310     throw e; 
#0 0.310     ^ 
#0 0.310  
#0 0.310 Error: Cannot find module 'turbo' 
#0 0.310 Require stack: 
#0 0.310 - /app/node_modules/turbo/node-platform.js 
#0 0.310 - /app/node_modules/turbo/bin/turbo 
#0 0.310     at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15) 
#0 0.310     at Function.resolve (node:internal/modules/helpers:118:19) 
#0 0.310     at downloadedBinPath (/app/node_modules/turbo/node-platform.js:44:44) 
#0 0.310     at generateBinPath (/app/node_modules/turbo/node-platform.js:67:15) 
#0 0.310     at Object.<anonymous> (/app/node_modules/turbo/bin/turbo:7:5) 
#0 0.310     at Module._compile (node:internal/modules/cjs/loader:1239:14) 
#0 0.310     at Module._extensions..js (node:internal/modules/cjs/loader:1293:10) 
#0 0.310     at Module.load (node:internal/modules/cjs/loader:1096:32) 
#0 0.310     at Module._load (node:internal/modules/cjs/loader:935:12) 
#0 0.310     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12) { 
#0 0.310   code: 'MODULE_NOT_FOUND', 
#0 0.310   requireStack: [ 
#0 0.310     '/app/node_modules/turbo/node-platform.js', 
#0 0.310     '/app/node_modules/turbo/bin/turbo' 
#0 0.310   ] 
#0 0.310 } 
#0 0.310  
#0 0.310 Node.js v19.4.0 
------ 
------ 
 > [with-docker-web builder 7/7] RUN turbo prune --scope=web --docker: 
#0 0.301 /app/node_modules/turbo/bin/turbo:13 
#0 0.301     throw e; 
#0 0.301     ^ 
#0 0.301  
#0 0.301 Error: Cannot find module 'turbo' 
#0 0.301 Require stack: 
#0 0.301 - /app/node_modules/turbo/node-platform.js 
#0 0.301 - /app/node_modules/turbo/bin/turbo 
#0 0.301     at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15) 
#0 0.301     at Function.resolve (node:internal/modules/helpers:118:19) 
#0 0.301     at downloadedBinPath (/app/node_modules/turbo/node-platform.js:44:44) 
#0 0.301     at generateBinPath (/app/node_modules/turbo/node-platform.js:67:15) 
#0 0.301     at Object.<anonymous> (/app/node_modules/turbo/bin/turbo:7:5) 
#0 0.301     at Module._compile (node:internal/modules/cjs/loader:1239:14) 
#0 0.301     at Module._extensions..js (node:internal/modules/cjs/loader:1293:10) 
#0 0.301     at Module.load (node:internal/modules/cjs/loader:1096:32) 
#0 0.301     at Module._load (node:internal/modules/cjs/loader:935:12) 
#0 0.301     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12) { 
#0 0.301   code: 'MODULE_NOT_FOUND', 
#0 0.301   requireStack: [ 
#0 0.301     '/app/node_modules/turbo/node-platform.js', 
#0 0.301     '/app/node_modules/turbo/bin/turbo' 
#0 0.301   ] 
#0 0.301 } 
#0 0.301  
#0 0.301 Node.js v19.4.0 
------ 
failed to solve: executor failed running [/bin/sh -c turbo prune --scope=web --docker]: exit code: 1 
➜  with-docker git:(main) ✗  
```

**Comment by tknickman** [comment]
@bibblebabl thanks for the report, a fix is available here https://github.com/vercel/turbo/pull/3301, it's a quick one - just include `node_modules` in the examples root `.dockerignore`. 

This was an oversight on our end originally, you should always be re-installing inside the container to ensure any platform specific dependencies (like `turbo`) get correctly installed. 

@aindong this will fix your issue as well - add a `.dockerignore` with:

```file=.dockerignore
node_modules
```

That ensures the globally installed turbo won't defer to a local turbo that was installed on the wrong system. 

You can find out more about turbo global vs local in our blog post https://turbo.build/blog/turbo-1-7-0#global-turbo

**Comment by aindong** [comment]
> @bibblebabl thanks for the report, a fix is available here #3301, it's a quick one - just include `node_modules` in the examples root `.dockerignore`.
> 
> This was an oversight on our end originally, you should always be re-installing inside the container to ensure any platform specific dependencies (like `turbo`) get correctly installed.
> 
> @aindong this will fix your issue as well - add a `.dockerignore` with:
> 
> ```
> node_modules
> ```
> 
> That ensures the globally installed turbo won't defer to a local turbo that was installed on the wrong system.
> 
> You can find out more about turbo global vs local in our blog post https://turbo.build/blog/turbo-1-7-0#global-turbo

Thanks! sorry for late replying and checking this ticket, I can confirm that the solution above fixes the issue <3

**Comment by MaxAst** [comment]
FWIW I just ran into the same problem, adding the `.dockerignore` file fixed the `Cannot find module 'turbo'` error, but then I got this error:
```
[+] Building 115.5s (18/22)                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                0.0s
 => => transferring dockerfile: 37B                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                   0.0s
 => => transferring context: 52B                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:alpine                                                                      0.7s
 => [internal] load build context                                                                                                   1.7s
 => => transferring context: 532.51kB                                                                                               1.7s
 => CACHED [installer  1/11] FROM docker.io/library/node:alpine@sha256:ab3603cb7934b21f1ffb522b1a1d538809516c6e4cd73b144716bc1830a  0.0s
 => CACHED [runner 2/5] WORKDIR /app                                                                                                0.0s
 => [runner 3/5] RUN addgroup --system --gid 1001 nodejs                                                                            0.4s
 => [installer  2/11] RUN apk add --no-cache libc6-compat                                                                           2.7s
 => [runner 4/5] RUN adduser --system --uid 1001 graphql                                                                            0.3s
 => [installer  3/11] RUN apk update                                                                                                2.5s 
 => [installer  4/11] WORKDIR /app                                                                                                  0.0s 
 => [installer  5/11] COPY .gitignore .gitignore                                                                                    0.0s
 => [builder 5/7] RUN yarn global add turbo                                                                                        41.7s
 => [builder 6/7] COPY . .                                                                                                          1.1s 
 => [builder 7/7] RUN turbo prune --scope=graphql-api --docker                                                                      0.4s 
 => [installer  6/11] COPY --from=builder /app/out/json/ .                                                                          0.0s 
 => [installer  7/11] COPY --from=builder /app/out/yarn.lock ./yarn.lock                                                            0.0s 
 => ERROR [installer  8/11] RUN yarn install                                                                                       66.1s 
------                                                                                                                                   
 > [installer  8/11] RUN yarn install:                                                                                                   
#18 0.315 yarn install v1.22.19                                                                                                          
#18 0.390 [1/5] Validating package.json...                                                                                               
#18 0.397 [2/5] Resolving packages...                                                                                                    
#18 0.590 [3/5] Fetching packages...                                                                                                     
#18 62.43 [4/5] Linking dependencies...
#18 62.44 warning "workspace-aggregator-91768be5-f176-4f58-a5a4-6d2f3c4a5cf5 > graphql-api > @pothos/plugin-prisma@3.40.1" has unmet peer dependency "@prisma/client@*".
#18 62.44 warning "workspace-aggregator-91768be5-f176-4f58-a5a4-6d2f3c4a5cf5 > graphql-api > @pothos/plugin-prisma@3.40.1" has unmet peer dependency "typescript@>=4.7.2".
#18 62.44 warning "workspace-aggregator-91768be5-f176-4f58-a5a4-6d2f3c4a5cf5 > graphql-api > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
#18 62.44 warning "workspace-aggregator-91768be5-f176-4f58-a5a4-6d2f3c4a5cf5 > graphql-api > ts-node-dev@2.0.0" has unmet peer dependency "typescript@*".
#18 64.85 [5/5] Building fresh packages...
#18 65.28 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#18 65.28 error /app/node_modules/bufferutil: Command failed.
#18 65.28 Exit code: 1
#18 65.28 Command: node-gyp-build
#18 65.28 Arguments: 
#18 65.28 Directory: /app/node_modules/bufferutil
#18 65.28 Output:
#18 65.28 gyp info it worked if it ends with ok
#18 65.28 gyp info using node-gyp@9.3.0
#18 65.28 gyp info using node@19.4.0 | linux | arm64
#18 65.28 gyp ERR! find Python 
#18 65.28 gyp ERR! find Python Python is not set from command line or npm configuration
#18 65.28 gyp ERR! find Python Python is not set from environment variable PYTHON
#18 65.28 gyp ERR! find Python checking if "python3" can be used
#18 65.28 gyp ERR! find Python - "python3" is not in PATH or produced an error
#18 65.28 gyp ERR! find Python checking if "python" can be used
#18 65.28 gyp ERR! find Python - "python" is not in PATH or produced an error
#18 65.28 gyp ERR! find Python 
#18 65.28 gyp ERR! find Python **********************************************************
#18 65.28 gyp ERR! find Python You need to install the latest version of Python.
#18 65.28 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#18 65.28 gyp ERR! find Python you can try one of the following options:
#18 65.28 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#18 65.28 gyp ERR! find Python   (accepted by both node-gyp and npm)
#18 65.28 gyp ERR! find Python - Set the environment variable PYTHON
#18 65.28 gyp ERR! find Python - Set the npm configuration variable python:
#18 65.28 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#18 65.28 gyp ERR! find Python For more information consult the documentation at:
#18 65.28 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#18 65.28 gyp ERR! find Python **********************************************************
#18 65.28 gyp ERR! find Python 
#18 65.28 gyp ERR! configure error 
#18 65.28 gyp ERR! stack Error: Could not find any Python installation to use
#18 65.28 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#18 65.28 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#18 65.28 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#18 65.28 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#18 65.28 gyp ERR! stack     at exithandler (node:child_process:427:5)
#18 65.28 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
#18 65.28 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#18 65.28 gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
#18 65.28 gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
#18 65.28 gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#18 65.28 gyp ERR! System Linux 5.15.49-linuxkit
#18 65.28 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#18 65.28 gyp ERR! cwd /app/node_modules/bufferutil
#18 65.28 gyp ERR! node -v v19.4.0
#18 65.28 gyp ERR! node-gyp -v v9.3.0
#18 65.28 gyp ERR! not ok
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
```

Fixed it by changing
```
FROM node:alpine AS installer
RUN apk add --no-cache libc6-compat
```
to
```
FROM node:alpine AS installer
RUN apk add --no-cache libc6-compat python3 make g++
```
