### ISSUE TITLE
Turbo 2.0 uses unstable Rust features (only available in nightly compiler)

### ISSUE THREAD

**Issue by kpcyrd** [vercel/turbo#8321]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

cargo build

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.0.1

### Describe the Bug

```
   Compiling turborepo-auth v0.1.0 (/build/turbo/src/turbo-2.0.1/crates/turborepo-auth)
error[E0658]: use of unstable library feature 'lazy_cell'
 --> crates/turborepo-lib/src/commands/scan.rs:1:11
  |
1 | use std::{sync::LazyLock, time::Duration};
  |           ^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
  = help: add `#![feature(lazy_cell)]` to the crate attributes to enable
  = note: this compiler was built on 2024-04-29; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'lazy_cell'
  --> crates/turborepo-lib/src/commands/scan.rs:12:25
   |
12 | static DIALOGUER_THEME: LazyLock<DialoguerTheme> = LazyLock::new(|| DialoguerTheme {
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable
   = note: this compiler was built on 2024-04-29; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'lazy_cell'
  --> crates/turborepo-lib/src/commands/scan.rs:12:52
   |
12 | static DIALOGUER_THEME: LazyLock<DialoguerTheme> = LazyLock::new(|| DialoguerTheme {
   |                                                    ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable
   = note: this compiler was built on 2024-04-29; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'lazy_cell'
  --> crates/turborepo-lib/src/commands/scan.rs:12:52
   |
12 | static DIALOGUER_THEME: LazyLock<DialoguerTheme> = LazyLock::new(|| DialoguerTheme {
   |                                                    ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable
   = note: this compiler was built on 2024-04-29; consider upgrading it if it is out of date

For more information about this error, try `rustc --explain E0658`.
error: could not compile `turborepo-lib` (lib) due to 4 previous errors
```

### Expected Behavior

Turbo compiles on stable Rust compilers.

Use https://docs.rs/lazy_static/latest/lazy_static/ instead.

### To Reproduce

```
cargo build
```

**Comment by NicholasLYang** [comment]
Hi @kpcyrd. We don't make any guarantees about the Rust toolchain that we use to build Turborepo. Is there a specific reason you wish to build using stable?

**Comment by kpcyrd** [comment]
Yes, I package turbo for Arch Linux (using the latest stable compiler):

https://archlinux.org/packages/extra/x86_64/turbo/

**Comment by NicholasLYang** [comment]
Sorry, using stable is not something we plan on doing. Were you able to package turbo with a stable compiler previously? We've used nightly basically since the beginning, so that's pretty surprising.

**Comment by getchoo** [comment]
@kpcyrd: This was introduced in https://github.com/vercel/turbo/commit/d4fd4fbbffc829fb78b8cc57f2bbd036b869a5a4, as the newer compiler version considers `lazy_cell` to be stable -- making the [previous feature flag](https://github.com/vercel/turbo/blob/a5a661791109f2b07286239b78a9868730259014/crates/turborepo-lib/src/lib.rs#L10) moot

Turbo can still be built with a stable Rust compiler by setting `RUSTC_BOOTSTRAP=1` and restoring that previous feature flag with a patch like [this](https://github.com/NixOS/nixpkgs/blob/0bc4da47bd1e37a170aca48d291b906b375e1262/pkgs/by-name/tu/turbo-unwrapped/enable-lazy_cell.patch). I've just [PR'd](https://github.com/NixOS/nixpkgs/pull/328295) this to nixpkgs, and I'd imagine it works for Arch as well

**Comment by kpcyrd** [comment]
Thanks, I've included your patch in https://gitlab.archlinux.org/archlinux/packaging/packages/turbo/-/commit/603b46146a38e6869f8faad8c5d336c4a0e605a3
